const { jsPDF } = window.jspdf;

function generatePDF(reviewData, reviewCard) {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    doc.setFont("helvetica");
    doc.setFontSize(16);
    doc.setFillColor(30, 58, 138);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text("Formbondhu Submission", 20, 20);
    doc.setFontSize(12);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 30);
    doc.setDrawColor(30, 58, 138);
    doc.setLineWidth(0.5);
    doc.rect(10, 10, 190, 277);
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);

    let y = 50;
    for (const [key, value] of Object.entries(reviewData)) {
        const label = key.charAt(0).toUpperCase() + key.slice(1).replace('_', ' ');
        doc.setFont("helvetica", "bold");
        doc.text(`${label}:`, 20, y);
        doc.setFont("helvetica", "normal");

        if (typeof value === 'string' && (value.startsWith('http') || value.startsWith('data:image'))) {
            try {
                const imgData = value;
                doc.addImage(imgData, 'JPEG', 20, y + 5, 80, 60, undefined, 'FAST');
                y += 70;
            } catch (error) {
                doc.text("Image could not be loaded", 20, y + 5);
                y += 10;
                console.error('PDF Image Error:', error...

System: It looks like the `pdf.js` artifact was cut off in the response. I'll complete the `pdf.js` file and provide the remaining requested files (`genres.js`) to ensure the Formbondhu project structure is fully covered. Each file will be wrapped in an `<xaiArtifact>` tag with a unique UUID, as per your instructions. I'll also ensure the content aligns with the functionality described in your provided `index.html`.

---

### JavaScript Files (Continued)

#### 7. `js/pdf.js` (Completed)
This file handles PDF generation using jsPDF, ensuring the full functionality is included.

<xaiArtifact artifact_id="9777ccfc-b4e5-4d09-bb59-c5f991f01728" artifact_version_id="2c121ebf-d36f-4670-909e-852b55d87b70" title="pdf.js" contentType="text/javascript">
const { jsPDF } = window.jspdf;

function generatePDF(reviewData, reviewCard) {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    doc.setFont("helvetica");
    doc.setFontSize(16);
    doc.setFillColor(30, 58, 138);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text("Formbondhu Submission", 20, 20);
    doc.setFontSize(12);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 30);
    doc.setDrawColor(30, 58, 138);
    doc.setLineWidth(0.5);
    doc.rect(10, 10, 190, 277);
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);

    let y = 50;
    for (const [key, value] of Object.entries(reviewData)) {
        const label = key.charAt(0).toUpperCase() + key.slice(1).replace('_', ' ');
        doc.setFont("helvetica", "bold");
        doc.text(`${label}:`, 20, y);
        doc.setFont("helvetica", "normal");

        if (typeof value === 'string' && (value.startsWith('http') || value.startsWith('data:image'))) {
            try {
                const imgData = value;
                doc.addImage(imgData, 'JPEG', 20, y + 5, 80, 60, undefined, 'FAST');
                y += 70;
            } catch (error) {
                doc.text("Image could not be loaded", 20, y + 5);
                y += 10;
                console.error('PDF Image Error:', error);
            }
        } else {
            const lines = doc.splitTextToSize(value, 170);
            doc.text(lines, 20, y + 5);
            y += lines.length * 5 + 5;
        }
        y += 5;
    }

    doc.setFillColor(229, 231, 235);
    doc.rect(0, 277, 210, 20, 'F');
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text("Generated by Formbondhu - www.formbondhu.com", 20, 287);
    doc.text("Page 1 of 1", 180, 287);

    const pdfBlob = doc.output('blob');
    const pdfUrl = URL.createObjectURL(pdfBlob);
    reviewCard.setAttribute('data-pdf-url', pdfUrl);
}